[package]
name = "day2"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
#criterion = {version = "0.8.0" , features = ["html_reports"] }
divan = "0.1.21"

[[bench]]
name="benchmarks"
harness = false
